# Generated by Django 5.2 on 2025-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('Reservation_time', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
