# Generated by Django 5.2 on 2025-05-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
