# Generated by Django 5.2 on 2025-05-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_movie_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
