# Generated by Django 5.2 on 2025-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
