# Generated by Django 5.2 on 2025-05-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('proficiency_level', models.CharField(max_length=50)),
                ('target_hours', models.IntegerField()),
            ],
        ),
    ]
