# Generated by Django 5.2 on 2025-05-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytracker',
            name='target_hours',
        ),
    ]
