# Generated by Django 5.2 on 2025-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTracker', '0002_remove_studytracker_target_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytracker',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studytracker',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytracker',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
