# Generated by Django 5.2 on 2025-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTracker', '0003_studytracker_completed_studytracker_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytracker',
            name='review',
        ),
        migrations.AddField(
            model_name='studytracker',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
