# Generated by Django 5.2 on 2025-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTracker', '0004_remove_studytracker_review_studytracker_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytracker',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
