# Generated by Django 5.2 on 2025-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyTracker', '0005_alter_studytracker_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytracker',
            name='start_date',
            field=models.DateField(),
        ),
    ]
