# Generated by Django 5.2 on 2025-05-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
