# Generated by Django 5.2 on 2025-05-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_alter_note_id'),
        ('StudyTracker', '0006_alter_studytracker_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='studyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='StudyTracker.studytracker'),
            preserve_default=False,
        ),
    ]
